.pre-commit-config.yaml
requirement.txt

add pre-commit
development
* https://ddangcoonfire.atlassian.net/browse/DDAN-18
add pre-commit for development

add pre-commit

---

experiment_scheduler/submitter/delete.py
experiment_scheduler/submitter/edit.py
experiment_scheduler/submitter/execute.py
experiment_scheduler/submitter/exs.py
experiment_scheduler/submitter/list.py
experiment_scheduler/submitter/status.py
sample.yaml
setup.py

Make initial format for submitter
Make initial format for submitter.
But, There is no code implementation.

[DDAN-19] merge to submmitter

---

experiment_scheduler/task_manager/task_manager.proto
experiment_scheduler/task_manager/task_manager_server.py

Add methods in task_manager_server of task_manager
Feature
* https://ddangcoonfire.atlassian.net/browse/DDAN-24

[DDAN-24] ADD Methods In task_manager 

---

.pre-commit-config.yaml
experiment_scheduler/experiment_scheduler.cfg
experiment_scheduler/master/master.py

add cfg file and logic for setting task_manager address

---

examples/quick_start.md

This PR includes example code.
documentation
* https://ddangcoonfire.atlassian.net/browse/DDAN-45
This PR includes first version of an example file

write first version example code

---

experiment_scheduler/master/master.py
experiment_scheduler/master/process_monitor.py

[DDAN-54] change process monitor multiprocessing structure to a class

---

experiment_scheduler/master/master.py
experiment_scheduler/master/process_monitor.py
experiment_scheduler/submitter/delete.py

- delete and list bug fix
* hot-fix
* https://ddangcoonfire.atlassian.net/browse/DDAN-49
* [] ADD JIRA ID ON PR TITLE (ex. [DDAN-1234] PR TITLE)

fix: delete and list bug fix

---

experiment_scheduler/master/master.py
experiment_scheduler/master/process_monitor.py

fix get all status completely
* hot-fix
* https://ddangcoonfire.atlassian.net/browse/DDAN-49

fix: get all status

---

experiment_scheduler/submitter/__init__.py
experiment_scheduler/submitter/exs.py

* add daemon option for servers 
-d (--daemon) option will run servers as daemon.
all logs are saved to each log file
* feature
* https://ddangcoonfire.atlassian.net/browse/DDAN-61

[DDAN-61] add daemon option for servers

---

experiment_scheduler/submitter/exs.py

Add Help Command
* improvement
* https://ddangcoonfire.atlassian.net/browse/DDAN-59
Need to Specify explanation later.

[DDAN-59] add help messages

---

experiment_scheduler/submitter/init_master.py
test/master/master.py
test/master/test_master.py
test/master/test_process_monitor.py

By refactoring, some methods are moved from master to pm or removed, added.
And some logics are changed at master and pm.
So, fix and add master & process monitor test adjusting refactoring.
Fix and Improvement

[DDAN 67] Fix master & process monitor test 

---

experiment_scheduler/task_manager/return_code.py
experiment_scheduler/task_manager/task_manager_server.py

Fix TaskManager to divide return code by OS
Fix
https://ddangcoonfire.atlassian.net/jira/software/c/projects/DDAN/boards/1?modal=detail&selectedIssue=DDAN-74

DDAN-74 fix return code

---

experiment_scheduler/task_manager/task_manager_server.py

make delete command really terminate task
bug-fix
* https://ddangcoonfire.atlassian.net/browse/DDAN-72

[DDAN 72] delete task really kills task now

---

experiment_scheduler/common/logging.py
experiment_scheduler/master/master.py
experiment_scheduler/master/process_monitor.py
experiment_scheduler/task_manager/__init__.py
experiment_scheduler/task_manager/task_manager_server.py
setup.py

* add new logging system
* review has done during monthly meeting.
* improvement
* https://ddangcoonfire.atlassian.net/browse/DDAN-73

[DDAN-73] add new logging

---

experiment_scheduler/experiment_scheduler.cfg
experiment_scheduler/task_manager/task_manager_server.py

* make running without GPU available
* hot-fix

make running without GPU available

---

experiment_scheduler/common/logging.py
requirement.txt
sample.yaml
setup.py

- fix bugs occurred during running on window (encoding error)
- change sample code to be available
- make `setup.py` install packages in `requirement.txt`.
hot-fix

hot-fix: fix bugs occurred during running on window

---

experiment_scheduler/master/master.py
experiment_scheduler/master/process_monitor.py

To make debug easier, print error message
hot-fix

hotfix: print error message

---

experiment_scheduler/master/master.py
experiment_scheduler/master/process_monitor.py
experiment_scheduler/submitter/__init__.py
experiment_scheduler/submitter/exs.py
experiment_scheduler/task_manager/task_manager_server.py

hotfix
hot-fix
hotfix: master becomes zombie process, process monitor critical error, hard coded task manager address
Did not followed rule for fast merge

hotfix: master becomes zombie process, process monitor critical error, hard coded task manager address

---

docker-compose.yaml
experiment_scheduler.dockerfile
experiment_scheduler/experiment_scheduler.cfg
experiment_scheduler/master/master.py
experiment_scheduler/task_manager/task_manager_server.py
master.dockerfile
script/off.bash
script/on.bash

For convenience of the users(including developers), we create the scripts to turn on master and task manger at the same time.
The master and task manager are initiated in different docker containers.
Improvement
*By running "./script/on.bash",* 
followings are executed automatically.
1) Docker image for experimenet-scheduler is built 
2) Master & task manager are initiated in the different docker containers.
You can run "./script/on.bash" multiple times whenever you want to turn off/on master & task manager. (Code changes will be reflected.)
*To check the status / logs of master & task,*
we can run "docker-compose …

Easy develop

---

experiment_scheduler/task_manager/task_manager_server.py

* fix a bug that error is raised when `exs list`
* hot-fix

hotfix: error is raised when exs list

---

experiment_scheduler/db_util/mixin.py

hotfix: remove raise

---

experiment_scheduler/db_util/mixin.py
test/db_util/test_mixin.py

- add db mixin class method example
- add db mixin class method unittest
* improvement
* https://ddangcoonfire.atlassian.net/browse/DDAN-66

[DDAN-66] add db mixin class method unittest

---

test/submitter/test_log.py

Test code for log of submitter
Test
https://ddangcoonfire.atlassian.net/jira/software/c/projects/DDAN/boards/1?modal=detail&selectedIssue=DDAN-103

Test: exs_log of submitter

---

README.md
experiment_scheduler/submitter/delete.py
experiment_scheduler/submitter/edit.py
experiment_scheduler/submitter/execute.py
experiment_scheduler/submitter/exs.py
experiment_scheduler/submitter/init_master.py
experiment_scheduler/submitter/log.py
experiment_scheduler/submitter/status.py

fix
* https://ddangcoonfire.atlassian.net/browse/DDAN-114
print help instead of error log in submitter
Print the argument error when there is a wrong argument value.

[DDAN-114] exs command error guide

---

docker-compose.yaml
experiment_scheduler/experiment_scheduler.cfg
experiment_scheduler/master/master.py
experiment_scheduler/submitter/__init__.py
experiment_scheduler/submitter/init_task_manager.py
experiment_scheduler/task_manager/task_manager_server.py

change default IP address as `localhost`.
Docker uses docker config now.
fix
* https://ddangcoonfire.atlassian.net/browse/DDAN-121

[DDAN-121] change default ip address

---

experiment_scheduler/db_util/task.py
experiment_scheduler/master/master.py
experiment_scheduler/master/process_monitor.py
experiment_scheduler/task_manager/grpc_task_manager/task_manager.proto
experiment_scheduler/task_manager/grpc_task_manager/task_manager_pb2.py
experiment_scheduler/task_manager/grpc_task_manager/task_manager_pb2.pyi
experiment_scheduler/task_manager/task.py
experiment_scheduler/task_manager/task_manager_server.py
sample.yaml

- fix: fix bug when finished task, status remained "Running" 
* fix
* https://ddangcoonfire.atlassian.net/jira/software/c/projects/DDAN/boards/1?selectedIssue=DDAN-106
* https://ddangcoonfire.atlassian.net/jira/software/c/projects/DDAN/boards/1?selectedIssue=DDAN-109

Ddan 106 bugfix updating status

---

experiment_scheduler/__init__.py
experiment_scheduler/master/master.py

release 1.1

---

experiment_scheduler/__init__.py
setup.py

fix: version

---

README.md

Add modulab logo
